NAME = AHCISCSIDriver_reloc
PROJECTVERSION = 1.1
LANGUAGE = English
CLASSES = AHCISCSI.m AHCIController.m
CFILES = AHCICore.c
HFILES = AHCISCSI.h AHCICore.h AHCIRegs.h PCIMSIClient.h PCIMSICore.h
OTHERSRCS = Makefile Makefile.preamble Makefile.postamble Makefile.driver_preamble Load_Commands.sect AHCI.ddm
MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = tool.make
SOURCEMODE = 444
-include Makefile.preamble
include $(MAKEFILEDIR)/$(MAKEFILE)
-include Makefile.postamble
-include Makefile.dependencies
